services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "my_volume_mongodb:/data/db"
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=carbon-calc
    networks:
      - carbon-calc

  spring-app:
    build: ./
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/carbon-calc
      - SERVER_PORT=8085
    depends_on:
      - mongo
    networks:
      - carbon-calc

networks:
  carbon-calc:
    driver: bridge

volumes:
  my_volume_mongodb: